### PR TITLE
Added Limit to Bank Deposits

### PR DESCRIPTION
**Pull request by ToeBeeBee**
BigDecimal allows deposits using exponents, this allows players to
deposit money to extreme decimal places possibly filling server
 memory. Hopefully this works, this is my first time contributing
 to a project and I'm not a trained programmer.

### CODE REVIEW

**Comment by jmhertlein** [comment]
Interesting, I hadn't considered this as an attack vector. Thank you for the patch.

I don't think this patch fully fixes it though. We need to validate the input string wherever we pass a user-generated string into the BigDecimal constructor (whereas this patch would only "squash" the bigdecimal after it had already potentially allocated a huge amount of system memory). 

I see quite a few usages of `new BigDecimal(String)`. Those would be where we need to target. 

I think the best approach is probably to first parse to long (with Long.parseLong()), and then pass that long into BigDecimal. I'm using BigDecimal here for its rounding behavior, rather than for its ability to hold huge numbers. 

With this approach, users trying to pass malicious input (like `"1E10000000000000000000000000"`) would instead get a NumberFormatException, instead of blowing up memory usage.

Would you like to work on this? I can give you repo access.

**Comment by ToeBeeBee** [comment]
I would be happy to implement a full fleshed patch for this. Thank you for the detailed response. I often find myself finding vulnerabilities but no knowing the right way to implement a solution. I'm extremely new to the whole git environment. Should I create a branch for the patch and commit to that or just commit changes to the master?

**Comment by jmhertlein** [comment]
Go ahead and follow Github's suggestion to "Add more commits by pushing to the depositFix branch on ToeBeeBee/MCTowns." 

The pull request will automatically include your additional commits. Then when it's ready, I can merge it here.

**Comment by jmhertlein** [comment]
Maven should handle all the dependencies. Unless me moving to my new domain recently broke them. I'll check that.

**Comment by jmhertlein** [comment]
Yeah, I had broken something when I moved some stuff from jmhertlein.net to josh.cafe. 

Vault also moved their repo at some point.

I fixed both these issues.

**Comment by jmhertlein** [comment]
And yeah, you're right. I guess the proper way to do it is to just use a regex. `^\d{1,10}(\.\d{1,10})?$` This pattern will allow then 10 digits, then potentially a dot and up to 10 more digits for the fractional part.

Ex:
  // Somewhere at the top of an appropriate class....
  private static final Pattern CURRENCY_PATTERN = Pattern.compile("^\d{1,10}(\.\d{1,10})?$");

  // then, wherever you need to validate an input string:
  public boolean checkString(String value) {
    return CURRENCY_PATTERN.matcher(value).matches();
  }

**Pull request closed without merging**
